name: geomed

services:
  backend:
    build:
      context: ../BACKEND
      dockerfile: Dockerfile
    env_file:
      - ../BACKEND/.env
    ports:
      - "8000:8000"
    volumes:
      - ../BACKEND:/app
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  telegram_bot:
    build:
      context: ../BACKEND
      dockerfile: Dockerfile
    env_file:
      - ../BACKEND/.env
    volumes:
      - ../BACKEND:/app
    restart: unless-stopped
    command: python start_telegram_bot.py

  frontend:
    build:
      context: ../FRONTEND
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3001:5173"
    depends_on:
      - backend
    volumes:
      - ../FRONTEND:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0
